language: python
python:
  - 2.7
  - 3.4
  - 3.5

sudo: false

addons:
  apt:
    packages:
      - python-numpy

install:
  - pip install nose
  - pip install -r requirements.txt

script:
  - nosetests

notifications:
 slack:
 email: false
