language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

sudo: false

addons:
  apt:
    packages:
      - python-numpy
      - python-scipy

env:
    - AUTOCLONE="y"

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi;
  - chmod +x miniconda.sh;
  - ./miniconda.sh -b;
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy nose
  - pip install -r requirements.txt

script:
  - nosetests

after_success:
  # - Build mybinder repo

notifications:
 slack: 3point:n4uGopqXrpbYFbslpV5z0tyO
 email: false
